name: E2E

on:
  push:
    branches: [main, master]

jobs:
  tests:
    name: End-to-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install Firebase CLI
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: "1//0gtX614rLiwSOCgYIARAAGBASNwF-L9IrEUMjMpu6w7tXXdLU9kJydq0hM2-jiXaJCqC5A_08x6cylqki-W9tN1Q7hhbohqxTHcs"

      - name: Set Firebase Emulator Port
        run: export FIRESTORE_EMULATOR_HOST="127.0.0.1:8888"

      - name: Run E2E test
        run: npm run test:e2e
